### Cadastrar um novo funcionario
POST https://localhost:5001/api/funcionarios/create
Content-Type: application/json

{
    "Nome" : "Joao",
    "Funcao": "Programador"
}

### Listar todos os funcionarios
GET https://localhost:5001/api/funcionarios